from __future__ import annotations

ALLOWED_TOOLS = {
    "llm_text_compose",
    "langsearch",
    "rag_knowledgebase",
    "web_fetch_page",
    "web_crawl_site",
    "web_crawl_site_whitelist",
    "mail_classify",
    "mail_compose_clarification",
    "gmail_fetch_inbox_mails",
    "gmail_fetch_unanswered_mails",
    "gmail_read_mail",
    "gmail_read_mail_thread",
    "gmail_answer_mail",
    "booking_reply_score",
    "customer_support_reply_score",
    "customer_support_policy_check",
    "customer_support_review_ticket_create",
    "customer_support_review_ticket_update",
    "assistent_profile_create",
    "assistent_profile_get",
    "assistent_profile_update",
    "assistent_profile_check",
}
