BASIC_TOOLS = {
    "read_file",
    "write_file",
    "rag_knowledgebase",
    "query_rag",
    "llm_smalltalk",
    "llm_summarize",
    "llm_compose",
    "pdf_export",
    "ppt_export",
    "websearch_table",
    "search_multitable",
    "websearch_videoanalyzer",
    "langsearch",
    #"google_search",
    "search_ebay",
    "view_website",
    "browse_website",
    "send_mail",
    "answer_mail",
    "fetch_inbox_mails",
    "fetch_unanswered_mails",
    "list_skills",
}

COMPETITIVE_ANALYSIS_TOOLS = {
    "competitive_parse_document",
    "competitive_quality_gate",
    "competitive_extract_product_profile",
    "competitive_extract_product_profile_v0_2",
    "competitive_extract_feature_claim_profile_quality_gate",
    "feature_claim_extraction_quality_gate",
    "competitive_generate_analysis_plan",
    "competitive_generate_analysis_plan_v0_2",
    "competitive_identify_competitors",
    "competitor_identification_v0_2",
    "competitor_search_v0_3",
    "competitor_search_v0_4",
    "competitor_search_v0_5",
    "competitor_product_results_v0_6",
    "competitor_products",
    "competitor_identification_quality_gate",
    "competitive_extract_competitor_profiles",
    "competitor_profile_extraction_quality_gate",
    "competitor_profile_extraction_v0_5",
    "competitor_profile_text_v0_6",
    "competitor_profile_extraction_v0_6",
    "competitive_merge_competitor_profiles",
    "competitive_verify_competitor_source_registry",
    "competitive_feature_matrix_gap_analysis",
    "feature_matrix_gap_analysis_v0_5",
    "competitive_feature_matrix_gap_analysis_quality_gate",
    "competitive_strategic_analysis",
    "stratetic_analysis_swot_positioning_v0_5",
    "final_report_generator_v0_5",
    "final_report_generator_v0_6",
    "competitive_generate_final_report",
    "competitive_publish_pdf_report",
    "professional_pdf_publischer_v0_6",
}

OFFER_FLOW = {
    "offerflow_step_1_intake",
    "offerflow_step_2_qualification",
    "offerflow_step_3_clarification",
    "offerflow_step_4_scope_mapping",
    "offerflow_step_5_resource_planning",
    "offerflow_step_6_pricing",
    "offerflow_step_7_validation",
}

def tools_allowed(tool_name: str) -> bool:
    name = str(tool_name or "").strip()
    return bool(name in BASIC_TOOLS or COMPETITIVE_ANALYSIS_TOOLS or name.startswith("agent_"))
